CREATE TABLE [dbo].[DIM_CLIENTE]
(
	[CD_CLIENTE] INT NOT NULL PRIMARY KEY, 
    [CD_CGCCPF] CHAR(18) NULL, 
    [DN_FANTASIA] CHAR(20) NULL, 
    [CD_MUNICIPIO] CHAR(5) NULL, 
    [DN_MUNICIPIO] CHAR(35) NULL, 
    [DN_BAIRRO] CHAR(15) NULL,
	[CD_CEP] INT NULL,
	[NR_ENDERECO] INT NULL,
    [CD_UF] CHAR(4) NULL, 
    [DN_UF] CHAR(20) NULL, 
	[TP_SITUACAO_SGE] CHAR NULL, 
    [VL_LIMITE_CRED] NUMERIC(16, 2) NULL, 
    [DT_IMPLANTACAO] DATE NULL, 
    [CD_CNAE] CHAR(7) NULL ,
    [DT_SINC] DATETIME NULL   
    
)
