CREATE TABLE [dbo].[DIM_LINHAS_AGRUPADAS]
(
	[CD_LINHA_COTA] INT NOT NULL PRIMARY KEY, 
    [DN_LINHA_COTA] VARCHAR(150) NULL, 
    [CD_DIVISAO] CHAR NULL, 
    [DT_SINC] DATETIME NULL, 
    CONSTRAINT [FK_DIM_LINHAS_AGRUPADAS_DIM_DIVISOES] FOREIGN KEY ([CD_DIVISAO]) REFERENCES [DIM_DIVISOES]([CD_DIVISAO])
)
