CREATE TABLE [dbo].[DIM_LINHAS_SGE]
(
	[CD_GRUPO] SMALLINT NOT NULL , 
    [CD_SUBGRUPO] SMALLINT NOT NULL, 
    [DN_GRUPO] CHAR(25) NULL, 
    [CD_DIVISAO] CHAR NULL, 
    [DT_SINC] DATETIME NULL, 
    CONSTRAINT [PK_DIM_LINHAS_SGE] PRIMARY KEY ([CD_GRUPO],[CD_SUBGRUPO]), 
    CONSTRAINT [FK_DIM_LINHAS_SGE_DIM_DIVISOES] FOREIGN KEY ([CD_DIVISAO]) REFERENCES [DIM_DIVISOES]([CD_DIVISAO])
)
