CREATE TABLE [dbo].[DIM_REPRESENTANTE]
(
    [CD_REPRES] INT NOT NULL, 
	[CD_CGCCPF] CHAR(18) NULL, 
    [DN_FANTASIA] CHAR(20) NOT NULL, 
    [TP_SITUACAO] CHAR NOT NULL, 
    [NR_CONTRATO] CHAR(20) NULL, 
    [CD_REGIAO] CHAR(6) NULL, 
    [CD_GERENTE] INT NULL, 
    [DT_SINC] DATETIME NULL, 
    CONSTRAINT [PK_DIM_REPRESENTANTE] PRIMARY KEY ([CD_REPRES]) 
)
