CREATE TABLE [dbo].[FATO_003]
(
		[Cod_Dia] NVARCHAR(50) NOT NULL , 
    [CD_FILIAL] SMALLINT NOT NULL, 
    [CD_REPRES] INT NOT NULL, 
    [CD_REGIAO] CHAR(6) NOT NULL,
    [VL_COTA] NUMERIC(16, 2) NULL, 
    [CD_LINHA_COTA] INT NOT NULL, 
    [CD_DIVISAO] CHAR NOT NULL, 
    [DT_SINC] DATETIME NULL, 
    CONSTRAINT [PK_FATO_003] PRIMARY KEY ([Cod_Dia], [CD_FILIAL], [CD_REPRES], [CD_REGIAO],[CD_LINHA_COTA], [CD_DIVISAO]), 
    CONSTRAINT [FK_FATO_003_DIM_DIVISOES] FOREIGN KEY ([CD_DIVISAO]) REFERENCES [DIM_DIVISOES]([CD_DIVISAO]), 
    CONSTRAINT [FK_FATO_003_DIM_TEMPO] FOREIGN KEY ([Cod_Dia]) REFERENCES [DIM_TEMPO]([Cod_Dia]), 
    CONSTRAINT [FK_FATO_003_DIM_REGIAO] FOREIGN KEY ([CD_REGIAO]) REFERENCES DIM_REGIAO([CD_REGIAO]), 
    CONSTRAINT [FK_FATO_003_DIM_LINHAS_AGRUPADAS] FOREIGN KEY ([CD_LINHA_COTA]) REFERENCES [DIM_LINHAS_AGRUPADAS]([CD_LINHA_COTA]), 
)
